#!/bin/bash

# Get the C file name from the command line argument
CFILE=$1

# Generate the assembly code and save it to a file with the same name as the C file, but with the .s extension
gcc -S -masm=intel "$CFILE" -o "${CFILE%.*}.s"
